"""
Seed data: 50 mock products across 10 categories.
Used both as DynamoDB seed and as in-memory fallback for local dev.
"""

import boto3

# from __MACOSX.urgentShopping.urgentShopping.backend.app.core.config import settings
from app.core.config import settings

PRODUCTS: list[dict] = [
    # ── Medicine ──────────────────────────────────────────────────────────────
    {
        "id": "p001",
        "name": "Paracetamol 500mg (10 tabs)",
        "category": "medicine",
        "price": 45.0,
        "unit": "strip",
        "eta_min": 28,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "fever headache pain relief tablet",
    },
    {
        "id": "p002",
        "name": "Ibuprofen 400mg (15 tabs)",
        "category": "medicine",
        "price": 72.0,
        "unit": "strip",
        "eta_min": 28,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "pain inflammation fever ibuprofen",
    },
    {
        "id": "p003",
        "name": "ORS Sachets (5 pack)",
        "category": "medicine",
        "price": 55.0,
        "unit": "pack",
        "eta_min": 28,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "dehydration electrolytes diarrhea rehydration",
    },
    {
        "id": "p004",
        "name": "Digital Thermometer",
        "category": "medicine",
        "price": 199.0,
        "unit": "piece",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "fever temperature thermometer",
    },
    {
        "id": "p005",
        "name": "Cold & Flu Relief Tablets (10 tabs)",
        "category": "medicine",
        "price": 89.0,
        "unit": "strip",
        "eta_min": 28,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "cold flu cough runny nose sore throat",
    },
    # ── Beverages ─────────────────────────────────────────────────────────────
    {
        "id": "p006",
        "name": "Nescafé Classic Instant Coffee 200g",
        "category": "beverages",
        "price": 189.0,
        "unit": "jar",
        "eta_min": 22,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "coffee morning caffeine instant nescafe",
    },
    {
        "id": "p007",
        "name": "Pepsi 2L Bottle",
        "category": "beverages",
        "price": 99.0,
        "unit": "bottle",
        "eta_min": 22,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "soft drink soda party cold pepsi drinks",
    },
    {
        "id": "p008",
        "name": "Minute Maid Orange Juice 1L",
        "category": "beverages",
        "price": 120.0,
        "unit": "pack",
        "eta_min": 22,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "juice orange vitamin c healthy morning",
    },
    {
        "id": "p009",
        "name": "Red Bull Energy Drink 250ml",
        "category": "beverages",
        "price": 115.0,
        "unit": "can",
        "eta_min": 22,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1622543956221-a39670b95d21?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "energy caffeine late night work focus",
    },
    {
        "id": "p010",
        "name": "Lipton Green Tea (25 bags)",
        "category": "beverages",
        "price": 85.0,
        "unit": "box",
        "eta_min": 22,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "tea healthy antioxidant calm relaxing",
    },
    # ── Dairy ─────────────────────────────────────────────────────────────────
    {
        "id": "p011",
        "name": "Amul Full Cream Milk 1L",
        "category": "dairy",
        "price": 66.0,
        "unit": "packet",
        "eta_min": 18,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "milk dairy morning breakfast amul",
    },
    {
        "id": "p012",
        "name": "Britannia Bread 400g",
        "category": "dairy",
        "price": 45.0,
        "unit": "pack",
        "eta_min": 18,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "bread breakfast toast sandwich",
    },
    {
        "id": "p013",
        "name": "Amul Butter 100g",
        "category": "dairy",
        "price": 58.0,
        "unit": "pack",
        "eta_min": 18,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "butter toast cooking baking",
    },
    {
        "id": "p014",
        "name": "Epigamia Greek Yogurt 90g",
        "category": "dairy",
        "price": 55.0,
        "unit": "cup",
        "eta_min": 18,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "yogurt healthy protein morning probiotic",
    },
    {
        "id": "p015",
        "name": "Amul Processed Cheese Slices (10 slices)",
        "category": "dairy",
        "price": 89.0,
        "unit": "pack",
        "eta_min": 18,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1486887396153-fa416525c108?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "cheese sandwich toast burger",
    },
    # ── Snacks ────────────────────────────────────────────────────────────────
    {
        "id": "p016",
        "name": "Lay's Classic Salted Chips 50g",
        "category": "snacks",
        "price": 20.0,
        "unit": "pack",
        "eta_min": 20,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "chips snacks party crisps lays",
    },
    {
        "id": "p017",
        "name": "Oreo Original Cookies 120g",
        "category": "snacks",
        "price": 40.0,
        "unit": "pack",
        "eta_min": 20,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "cookies biscuits snacks party oreo",
    },
    {
        "id": "p018",
        "name": "Kurkure Masala Munch 90g",
        "category": "snacks",
        "price": 20.0,
        "unit": "pack",
        "eta_min": 20,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1599490659213-e2b9527ec087?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "snacks masala crunchy party kurkure",
    },
    {
        "id": "p019",
        "name": "Maggi 2-Minute Noodles (4 pack)",
        "category": "snacks",
        "price": 68.0,
        "unit": "pack",
        "eta_min": 20,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "noodles quick meal hunger maggi comfort",
    },
    {
        "id": "p020",
        "name": "Parle-G Glucose Biscuits 800g",
        "category": "snacks",
        "price": 60.0,
        "unit": "pack",
        "eta_min": 20,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "biscuits tea snack parle glucose",
    },
    # ── Personal Care ─────────────────────────────────────────────────────────
    {
        "id": "p021",
        "name": "Dettol Antiseptic Liquid 250ml",
        "category": "personal_care",
        "price": 139.0,
        "unit": "bottle",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "antiseptic wound cut cleaning hygiene dettol",
    },
    {
        "id": "p022",
        "name": "Band-Aid Bandages (20 strips)",
        "category": "personal_care",
        "price": 75.0,
        "unit": "box",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "bandage wound cut first aid plaster",
    },
    {
        "id": "p023",
        "name": "Vicks VapoRub 25g",
        "category": "personal_care",
        "price": 89.0,
        "unit": "jar",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "cold congestion breathing cough blocked nose vicks",
    },
    {
        "id": "p024",
        "name": "Colgate Strong Teeth Toothpaste 200g",
        "category": "personal_care",
        "price": 89.0,
        "unit": "tube",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1559599189-fe84dea4eb79?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "toothpaste dental hygiene morning colgate",
    },
    {
        "id": "p025",
        "name": "Dove Soap Bar 75g (Pack of 3)",
        "category": "personal_care",
        "price": 120.0,
        "unit": "pack",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1607006342440-b7095a8e0f22?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "soap bath hygiene shower dove",
    },
    # ── Cleaning ──────────────────────────────────────────────────────────────
    {
        "id": "p026",
        "name": "Colin Glass Cleaner 500ml",
        "category": "cleaning",
        "price": 119.0,
        "unit": "bottle",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1585421514738-ee9479e3a786?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "glass cleaner cleaning spray colin",
    },
    {
        "id": "p027",
        "name": "Harpic Power Plus Toilet Cleaner 500ml",
        "category": "cleaning",
        "price": 99.0,
        "unit": "bottle",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "toilet cleaner bathroom cleaning harpic",
    },
    {
        "id": "p028",
        "name": "Lizol Disinfectant Floor Cleaner 500ml",
        "category": "cleaning",
        "price": 129.0,
        "unit": "bottle",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "floor cleaner disinfectant cleaning lizol",
    },
    {
        "id": "p029",
        "name": "Scotch-Brite Scrub Pad (3 pack)",
        "category": "cleaning",
        "price": 45.0,
        "unit": "pack",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "scrub pad kitchen cleaning dishes utensils",
    },
    {
        "id": "p030",
        "name": "Surf Excel Matic Detergent 1kg",
        "category": "cleaning",
        "price": 279.0,
        "unit": "pack",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1610557892470-55d9e80e0b96?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "laundry detergent washing clothes surf excel",
    },
    # ── Baby Care ─────────────────────────────────────────────────────────────
    {
        "id": "p031",
        "name": "Pampers Baby Dry Diapers M (30 count)",
        "category": "baby",
        "price": 549.0,
        "unit": "pack",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1595254555192-b4b3b8915655?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "diapers baby nappy pampers",
    },
    {
        "id": "p032",
        "name": "Johnson's Baby Powder 200g",
        "category": "baby",
        "price": 175.0,
        "unit": "bottle",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1515488042361-404e9250afef?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "baby powder skin care johnson",
    },
    {
        "id": "p033",
        "name": "Mamy Poko Pants XL (40 count)",
        "category": "baby",
        "price": 659.0,
        "unit": "pack",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1595254555192-b4b3b8915655?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "diapers pants baby toddler mamy poko",
    },
    # ── Home & Emergency ──────────────────────────────────────────────────────
    {
        "id": "p034",
        "name": "Eveready AA Batteries (4 pack)",
        "category": "home",
        "price": 79.0,
        "unit": "pack",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "batteries power outage emergency torch aa",
    },
    {
        "id": "p035",
        "name": "Havells LED Torch Flashlight",
        "category": "home",
        "price": 299.0,
        "unit": "piece",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1554189097-ffe88e998a2b?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "torch flashlight power outage emergency light",
    },
    {
        "id": "p036",
        "name": "Wax Candles Pack (12 pcs)",
        "category": "home",
        "price": 59.0,
        "unit": "pack",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "candles power outage light emergency",
    },
    {
        "id": "p037",
        "name": "Disposable Paper Plates (50 pcs)",
        "category": "home",
        "price": 99.0,
        "unit": "pack",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "plates party disposable guests",
    },
    {
        "id": "p038",
        "name": "Disposable Plastic Cups (50 pcs)",
        "category": "home",
        "price": 75.0,
        "unit": "pack",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1594897030264-ab7d87efc473?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "cups party disposable drinks guests",
    },
    # ── Electronics ───────────────────────────────────────────────────────────
    {
        "id": "p039",
        "name": "Ambrane 10000mAh Power Bank",
        "category": "electronics",
        "price": 799.0,
        "unit": "piece",
        "eta_min": 40,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1609592424109-dd77884d59a8?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "power bank charging mobile emergency battery",
    },
    {
        "id": "p040",
        "name": "USB Type-C Charging Cable 1m",
        "category": "electronics",
        "price": 199.0,
        "unit": "piece",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "charger cable usb type-c mobile android",
    },
    {
        "id": "p041",
        "name": "Universal Mobile Screen Guard",
        "category": "electronics",
        "price": 149.0,
        "unit": "piece",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1581090700227-13617d9d92e8?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "screen protector mobile phone tempered glass",
    },
    # ── Grocery Staples ───────────────────────────────────────────────────────
    {
        "id": "p042",
        "name": "Aashirvaad Whole Wheat Atta 5kg",
        "category": "grocery",
        "price": 279.0,
        "unit": "bag",
        "eta_min": 30,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "wheat flour cooking roti chapati atta",
    },
    {
        "id": "p043",
        "name": "Fortune Sunflower Oil 1L",
        "category": "grocery",
        "price": 149.0,
        "unit": "bottle",
        "eta_min": 28,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "cooking oil sunflower fortune",
    },
    {
        "id": "p044",
        "name": "Tata Salt 1kg",
        "category": "grocery",
        "price": 24.0,
        "unit": "pack",
        "eta_min": 22,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "salt cooking basic essential tata",
    },
    {
        "id": "p045",
        "name": "MDH Garam Masala 50g",
        "category": "grocery",
        "price": 55.0,
        "unit": "pack",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "spice masala cooking garam mdh",
    },
    {
        "id": "p046",
        "name": "Knorr Chicken Soup Mix 44g",
        "category": "grocery",
        "price": 45.0,
        "unit": "pack",
        "eta_min": 25,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "soup chicken sick comfort food knorr warm",
    },
    # ── Fresh Produce ─────────────────────────────────────────────────────────
    {
        "id": "p047",
        "name": "Bananas 6 pcs (~500g)",
        "category": "fresh",
        "price": 49.0,
        "unit": "bunch",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "fruit banana healthy morning breakfast energy",
    },
    {
        "id": "p048",
        "name": "Tomatoes 500g",
        "category": "fresh",
        "price": 30.0,
        "unit": "pack",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "vegetable tomato cooking fresh salad",
    },
    {
        "id": "p049",
        "name": "Onions 1kg",
        "category": "fresh",
        "price": 45.0,
        "unit": "bag",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "vegetable onion cooking basic essential",
    },
    {
        "id": "p050",
        "name": "Lemons 6 pcs",
        "category": "fresh",
        "price": 20.0,
        "unit": "pack",
        "eta_min": 35,
        "in_stock": True,
        "image_url": "https://images.unsplash.com/photo-1590502593747-42a996133562?auto=format&fit=crop&w=400&h=400&q=80",
        "tags": "lemon citrus vitamin c fresh juice nimbu",
    },
]

# Maps time-of-day context → preferred categories for recommendations
TIME_BASED_CATEGORIES: dict[str, list[str]] = {
    "morning": ["dairy", "beverages", "fresh"],
    "midday": ["grocery", "snacks", "fresh"],
    "afternoon": ["beverages", "snacks", "grocery"],
    "evening": ["snacks", "beverages", "cleaning"],
    "night": ["medicine", "snacks", "personal_care"],
}


def seed_products() -> None:
    """Write all mock products to DynamoDB."""
    dynamodb = boto3.resource("dynamodb", region_name=settings.aws_region)
    table = dynamodb.Table(settings.dynamodb_products_table)

    from decimal import Decimal

    print(f"Seeding {len(PRODUCTS)} products → {settings.dynamodb_products_table} ...")
    with table.batch_writer() as batch:
        for product in PRODUCTS:
            item = dict(product)
            if "price" in item:
                item["price"] = Decimal(str(item["price"]))
            batch.put_item(Item=item)
    print("✅ Seed complete.")


if __name__ == "__main__":
    seed_products()
